INSERT INTO Users (User_Id, username, Hashed_Password) Values (1, 'shelley.nason', '$shiro1$SHA-256$500000$sdE2TVtab0IUCuXN0sgcvg==$nDMeOhrLsBqGZgJrC9V7PugC6kaJrcpfRXYqAYbdZxk=');
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('02-01-2015', 'dd-MM-yyyy'), 'New York Times Digital', 7.50);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('30-12-2014', 'dd-MM-yyyy'), 'Central Co-op', 24.64);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('29-12-2014', 'dd-MM-yyyy'), 'QFC', 35.94);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('29-12-2014', 'dd-MM-yyyy'), 'Rhapsody', 9.99);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('24-12-2014', 'dd-MM-yyyy'), 'Central Co-op', 47.04);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('23-12-2014', 'dd-MM-yyyy'), 'Central Co-op', 6.83);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('22-12-2014', 'dd-MM-yyyy'), 'QFC', 23.26);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('22-12-2014', 'dd-MM-yyyy'), 'Target', 22.98);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('22-12-2014', 'dd-MM-yyyy'), 'QFC', 23.31);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('19-12-2014', 'dd-MM-yyyy'), 'Amazon', 21.28);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('18-12-2014', 'dd-MM-yyyy'), 'Central Co-op', 29.00);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('17-12-2014', 'dd-MM-yyyy'), 'T-Mobile', 10.75);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('16-12-2014', 'dd-MM-yyyy'), 'Central Co-op', 20.67);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('15-12-2014', 'dd-MM-yyyy'), 'QFC', 19.70);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('15-12-2014', 'dd-MM-yyyy'), 'Container Store', 14.75);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('15-12-2014', 'dd-MM-yyyy'), 'Quinn's Pub', 35.56);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('12-12-2014', 'dd-MM-yyyy'), 'Ikea', 27.36);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('11-12-2014', 'dd-MM-yyyy'), 'Mastercard', 877.58);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('10-12-2014', 'dd-MM-yyyy'), 'Cosmedic Skin', 70.00);
INSERT INTO Expenses (User_Id, Date, Description, Amount) Values (1, parsedatetime('10-12-2014', 'dd-MM-yyyy'), 'Central Co-op', 14.24);